app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__, template_folder='templates', static_folder='static')

from . import views

app/main/views.py
from flask import render_template, flash, redirect, url_for, request, jsonify, render_template, abort
from . import main_bp as bp
from .form import LoginForm, ServiceForm
from ..models import User, AuthLog, db, Service
from flask_login import current_user, login_user, login_required, logout_user


@bp.route('/', methods=['GET'])
def index():
    services = Service.query.all()
    filtered = []
    for service in services:
        if current_user.is_authenticated is False and service.admin:
            pass
        else:
            filtered.append(service)
    return render_template('index.html', services=filtered)


@bp.route('/auth_log', methods=['GET'])
@login_required
def authentication_log():
    auth_log = AuthLog.query.all()
    return render_template('auth_log.html', auths=auth_log)


@bp.route('/delete_log_activity', methods=['GET'])
@login_required
def delete_log_entry():
    del_id = request.args.get('id')
    AuthLog.query.filter_by(id=del_id).delete()
    db.session.commit()
    return redirect(url_for('main.authentication_log'))


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.compare_hashes(form.password.data):
            flash('Invalid username or password')
            log_activity("Failure", form.username.data)
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        log_activity("Success", form.username.data)
        return redirect(url_for('main.index'))
    return render_template('login.html', title='Sign In', form=form)


@bp.route('/service', methods=['GET', 'POST'])
@login_required
def add_service():
    """ TODO ERROR MESSAGES"""
    form = ServiceForm()
    if form.validate_on_submit():
        user = Service(name=form.name.data, description=form.description.data, github=form.github.data, status=int(form.status.data),
                       port=form.port.data, admin=int(form.admin.data), domain=form.domain.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('add_service.html', title='Add service', form=form)


@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


def log_activity(status, username, ip=None,):
    auth = AuthLog(status, username, ip)
    db.session.add(auth)
    db.session.commit()

app/main/templates/add_service.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Signin Template for Bootstrap</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='signin.css') }}">

  </head>
  <body class="text-center">
        <div class="container">
            <h1>Service information</h1>
            <form action="" method="post" novalidate>
                {{ form.hidden_tag() }}
                <p>
                    {{ form.name.label }}<br>
                    {{ form.name(size=64) }}
                </p>
                <p>
                    {{ form.description.label }}<br>
                    {{ form.description(cols="35", rows="20")  }}
                </p>
                <p>{{ form.github.label }}<br>
                    {{ form.github(size=64) }}
                </p>
                <p>{{ form.domain.label }}<br>
                    {{ form.domain(size=32) }}
                </p>
                <p>{{ form.port.label }}<br>
                    {{ form.port(size=11) }}
                </p>
                <p>{{ form.status() }} {{ form.status.label }}</p>
                <p>{{ form.admin() }} {{ form.admin.label }}</p>
                <p>{{ form.submit() }}</p>
            </form>
            {% if get_flashed_messages() %}
                <p class="my-0 font-weight-normal text-danger">
                    {% for message in get_flashed_messages() %}
                        {{ message }}
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </body>
</html>

app/main/templates/auth_log.html
{% extends "base.html" %}
{% block content %}
    <h1>Activity log</h1>
    {% for auth in auths %}
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            {% if auth.status == "Failure" %}
                <h4 class="my-0 font-weight-normal text-danger" >{{ auth.status }}</h4>
              {% else %}
                <h4 class="my-0 font-weight-normal text-success" >{{ auth.status }}</h4>
              {% endif %}
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
                <li>User: {{ auth.username }}</li>
                <li>IP: {{ auth.ip }}</li>
              <li>Time: {{ auth.log_time }}</li>
              <li><a class="btn btn-danger mt-3" href="{{ url_for('main.delete_log_entry') }}?id={{ auth.id }}" role="button">Delete</a></li>
            </ul>
          </div>
        </div>
    {% endfor %}
{% endblock %}

app/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>panel</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
    <body class="theme-color">
    <header>
        <div class="collapse bg-dark" id="navbarHeader">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">This is the "admin" template for this server. Here you can find all the projects that lives in here</p>
              </div>
              <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Admin</h4>
                <ul class="list-unstyled">
                  <li><a href="#" class="text-white"></a></li>
                  <li><a href="{{ url_for('main.login') }}" class="text-white">LogIn</a></li>
                  <li><a href="{{ url_for('main.logout') }}" class="text-white">LogOut</a></li>
                    <li><a href="{{ url_for('main.add_service') }}" class="text-white">AddService</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="navbar navbar-dark bg-dark box-shadow">
          <div class="container d-flex">
            <a href="{{ url_for('main.index') }}" class="navbar-brand text-secondary d-flex align-items-center">Home</a>
              <a href="{{ url_for('main.authentication_log') }}" class="navbar-brand  text-secondary d-flex align-items-center">Auths</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </div>
      </header>
  
      <main role="main">
          <div class="album py-5 bg-light" id="main">
          <div class="container" id="main-height">
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>

    <footer class="text-muted fixed-bottom theme-color">
        <div class="container">
          <h5 class="text-white">GitHub</h5><a href="https://github.com/Risto12" class="text-secondary">Risto12</a>
        </div>
      </footer>
  
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js" integrity="sha384-3qaqj0lc6sV/qpzrc1N5DC6i1VRn/HyX4qdPaiEFbn54VjQBEU341pvjz7Dv3n6P" crossorigin="anonymous"></script>
    </body>
</html>

app/main/templates/index.html
{% extends "base.html" %}
{% block content %}
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Welcome to vesanto.dev</h1>
            <p>Below are all the services currently running on this server</p>
        </div>
      </section>
    <div class="container mt-4 jumbotron">
        <div class="row">
        {% for service in services %}
            <div class="card mb-4 box-shadow mr-3">
              <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-success" >{{ service.name }}</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Description: {{ service.description }}</li>
                    <li>Updated: {{ service.updated }}</li>
                    <li>Domain: {{ service.domain }}</li>
                    <li>Port: {{ service.port }}</li>
                    <li>Status: {{ service.status }}</li>
                    <li>Admin: {{ service.admin }}</li>
                    <li>Github:<a href="{{ service.github }}">link</a></li>
                </ul>
              </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

app/main/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Signin Template for Bootstrap</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='signin.css') }}">

  </head>
  <body class="text-center">
        <div class="container">
            <h1>Sign In</h1>
            <form action="" method="post" novalidate>
                {{ form.hidden_tag() }}
                <p>
                    {{ form.username.label }}<br>
                    {{ form.username(size=32) }}
                </p>
                <p>
                    {{ form.password.label }}<br>
                    {{ form.password(size=32) }}
                </p>
                <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
                <p>{{ form.submit() }}</p>
            </form>
            {% if get_flashed_messages() %}
                <p class="my-0 font-weight-normal text-danger">
                    {% for message in get_flashed_messages() %}
                        {{ message }}
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </body>
</html>